Running in wrapper mode for '12'

Running python job.

[name: "CPU-QUOTA"
int_val: 15
int_val: 24
int_val: 78
int_val: 16
int_val: 87
int_val: 12
int_val: 46
, name: "DISK"
int_val: 15
int_val: 11
int_val: 25
int_val: 37
int_val: 18
int_val: 11
int_val: 6
, name: "MEMORY"
int_val: 37
int_val: 21
int_val: 33
int_val: 25
int_val: 10
int_val: 19
int_val: 12
, name: "NET"
int_val: 30
int_val: 17
int_val: 31
int_val: 28
int_val: 14
int_val: 13
int_val: 13
]
The paramters are {u'CPU-QUOTA': array([15, 24, 78, 16, 87, 12, 46]), u'NET': array([30, 17, 31, 28, 14, 13, 13]), u'DISK': array([15, 11, 25, 37, 18, 11,  6]), u'MEMORY': array([37, 21, 33, 25, 10, 19, 12])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b7ac3f8>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
