Running in wrapper mode for '47'

Running python job.

[name: "CPU-QUOTA"
int_val: 35
int_val: 71
int_val: 14
int_val: 33
int_val: 20
int_val: 47
int_val: 44
, name: "DISK"
int_val: 9
int_val: 19
int_val: 32
int_val: 9
int_val: 5
int_val: 29
int_val: 18
, name: "MEMORY"
int_val: 12
int_val: 21
int_val: 16
int_val: 15
int_val: 27
int_val: 34
int_val: 25
, name: "NET"
int_val: 40
int_val: 33
int_val: 13
int_val: 37
int_val: 16
int_val: 5
int_val: 39
]
The paramters are {u'CPU-QUOTA': array([35, 71, 14, 33, 20, 47, 44]), u'NET': array([40, 33, 13, 37, 16,  5, 39]), u'DISK': array([ 9, 19, 32,  9,  5, 29, 18]), u'MEMORY': array([12, 21, 16, 15, 27, 34, 25])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b7b8908>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.45 seconds.
