Running in wrapper mode for '44'

Running python job.

[name: "CPU-QUOTA"
int_val: 11
int_val: 47
int_val: 38
int_val: 57
int_val: 44
int_val: 71
int_val: 20
, name: "DISK"
int_val: 36
int_val: 28
int_val: 23
int_val: 36
int_val: 14
int_val: 20
int_val: 9
, name: "MEMORY"
int_val: 39
int_val: 12
int_val: 7
int_val: 24
int_val: 36
int_val: 7
int_val: 34
, name: "NET"
int_val: 13
int_val: 24
int_val: 40
int_val: 10
int_val: 7
int_val: 14
int_val: 30
]
The paramters are {u'CPU-QUOTA': array([11, 47, 38, 57, 44, 71, 20]), u'NET': array([13, 24, 40, 10,  7, 14, 30]), u'DISK': array([36, 28, 23, 36, 14, 20,  9]), u'MEMORY': array([39, 12,  7, 24, 36,  7, 34])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b74c680>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
