Running in wrapper mode for '101'

Running python job.

[name: "CPU-QUOTA"
int_val: 75
int_val: 84
int_val: 11
int_val: 54
int_val: 29
int_val: 42
int_val: 42
, name: "DISK"
int_val: 29
int_val: 31
int_val: 12
int_val: 38
int_val: 6
int_val: 38
int_val: 23
, name: "MEMORY"
int_val: 40
int_val: 12
int_val: 6
int_val: 9
int_val: 39
int_val: 8
int_val: 12
, name: "NET"
int_val: 20
int_val: 24
int_val: 6
int_val: 25
int_val: 29
int_val: 19
int_val: 24
]
The paramters are {u'CPU-QUOTA': array([75, 84, 11, 54, 29, 42, 42]), u'NET': array([20, 24,  6, 25, 29, 19, 24]), u'DISK': array([29, 31, 12, 38,  6, 38, 23]), u'MEMORY': array([40, 12,  6,  9, 39,  8, 12])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b75e8c0>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.47 seconds.
