Running in wrapper mode for '52'

Running python job.

[name: "CPU-QUOTA"
int_val: 17
int_val: 17
int_val: 8
int_val: 27
int_val: 98
int_val: 53
int_val: 26
, name: "DISK"
int_val: 7
int_val: 26
int_val: 25
int_val: 20
int_val: 25
int_val: 40
int_val: 25
, name: "MEMORY"
int_val: 32
int_val: 24
int_val: 9
int_val: 26
int_val: 33
int_val: 32
int_val: 9
, name: "NET"
int_val: 19
int_val: 27
int_val: 28
int_val: 17
int_val: 19
int_val: 39
int_val: 32
]
The paramters are {u'CPU-QUOTA': array([17, 17,  8, 27, 98, 53, 26]), u'NET': array([19, 27, 28, 17, 19, 39, 32]), u'DISK': array([ 7, 26, 25, 20, 25, 40, 25]), u'MEMORY': array([32, 24,  9, 26, 33, 32,  9])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b753128>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
