Running in wrapper mode for '130'

Running python job.

[name: "CPU-QUOTA"
int_val: 67
int_val: 7
int_val: 34
int_val: 56
int_val: 96
int_val: 10
int_val: 23
, name: "DISK"
int_val: 13
int_val: 32
int_val: 34
int_val: 19
int_val: 25
int_val: 17
int_val: 20
, name: "MEMORY"
int_val: 12
int_val: 39
int_val: 30
int_val: 19
int_val: 26
int_val: 21
int_val: 11
, name: "NET"
int_val: 20
int_val: 32
int_val: 40
int_val: 35
int_val: 9
int_val: 13
int_val: 31
]
The paramters are {u'CPU-QUOTA': array([67,  7, 34, 56, 96, 10, 23]), u'NET': array([20, 32, 40, 35,  9, 13, 31]), u'DISK': array([13, 32, 34, 19, 25, 17, 20]), u'MEMORY': array([12, 39, 30, 19, 26, 21, 11])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7f244e236638>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.50 seconds.
