Running in wrapper mode for '284'

Running python job.

[name: "CPU-QUOTA"
int_val: 8
int_val: 25
int_val: 51
int_val: 58
int_val: 11
int_val: 41
int_val: 90
, name: "DISK"
int_val: 7
int_val: 24
int_val: 20
int_val: 36
int_val: 39
int_val: 8
int_val: 14
, name: "MEMORY"
int_val: 6
int_val: 22
int_val: 17
int_val: 23
int_val: 11
int_val: 39
int_val: 19
, name: "NET"
int_val: 16
int_val: 16
int_val: 25
int_val: 13
int_val: 40
int_val: 18
int_val: 35
]
The paramters are {u'CPU-QUOTA': array([ 8, 25, 51, 58, 11, 41, 90]), u'NET': array([16, 16, 25, 13, 40, 18, 35]), u'DISK': array([ 7, 24, 20, 36, 39,  8, 14]), u'MEMORY': array([ 6, 22, 17, 23, 11, 39, 19])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
Setting cpu quota to 62500 out of 250000
STRESSING VM_IP 13.56.14.158 AND CONTAINER d824175f3227, NET 81920.0
STRESSING VM_IP 13.56.14.158 AND CONTAINER d824175f3227, DISK 20132659.2
STRESSING VM_IP 13.56.14.158 AND CONTAINER d824175f3227, MEMORY 825000000.0
Recovering the memory utilization
Setting cpu quota to 20000 out of 250000
STRESSING VM_IP 13.56.14.158 AND CONTAINER cd40be619604, NET 81920.0
STRESSING VM_IP 13.56.14.158 AND CONTAINER cd40be619604, DISK 5872025.6
STRESSING VM_IP 13.56.14.158 AND CONTAINER cd40be619604, MEMORY 225000000.0
Recovering the memory utilization
Setting cpu quota to 127500 out of 250000
STRESSING VM_IP 13.56.14.158 AND CONTAINER c21ccad5695a, NET 128000.0
STRESSING VM_IP 13.56.14.158 AND CONTAINER c21ccad5695a, DISK 16777216.0
STRESSING VM_IP 13.56.14.158 AND CONTAINER c21ccad5695a, MEMORY 637500000.0
Recovering the memory utilization
Setting cpu quota to 20000 out of 250000
STRESSING VM_IP 18.144.43.31 AND CONTAINER 01a0240fb06e, NET 81920.0
STRESSING VM_IP 18.144.43.31 AND CONTAINER 01a0240fb06e, DISK 5872025.6
STRESSING VM_IP 18.144.43.31 AND CONTAINER 01a0240fb06e, MEMORY 225000000.0
Recovering the memory utilization
Setting cpu quota to 127500 out of 250000
STRESSING VM_IP 18.144.43.31 AND CONTAINER d4df0b3c1712, NET 128000.0
STRESSING VM_IP 18.144.43.31 AND CONTAINER d4df0b3c1712, DISK 16777216.0
STRESSING VM_IP 18.144.43.31 AND CONTAINER d4df0b3c1712, MEMORY 637500000.0
Recovering the memory utilization
Using 5 trials
INVALID EXPERIMENT TYPE: todo-app

----------------------------------------
Problem running the job:
(<type 'exceptions.SystemExit'>, SystemExit(None,), <traceback object at 0x7f4038492560>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 204, in explore_spearmint
    experiment_results = run_experiment.measure_runtime(workload_config, experiment_trials)
  File "/home/ubuntu/throttlebot/src/run_experiment.py", line 37, in measure_runtime
    exit()
  File "/usr/lib/python2.7/site.py", line 375, in __call__
    raise SystemExit(code)
SystemExit: None
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 15.51 seconds.
