Running in wrapper mode for '143'

Running python job.

[name: "CPU-QUOTA"
int_val: 40
int_val: 64
int_val: 73
int_val: 29
int_val: 87
int_val: 25
int_val: 14
, name: "DISK"
int_val: 32
int_val: 29
int_val: 35
int_val: 38
int_val: 21
int_val: 9
int_val: 28
, name: "MEMORY"
int_val: 35
int_val: 36
int_val: 24
int_val: 6
int_val: 9
int_val: 20
int_val: 8
, name: "NET"
int_val: 30
int_val: 40
int_val: 39
int_val: 7
int_val: 39
int_val: 19
int_val: 29
]
The paramters are {u'CPU-QUOTA': array([40, 64, 73, 29, 87, 25, 14]), u'NET': array([30, 40, 39,  7, 39, 19, 29]), u'DISK': array([32, 29, 35, 38, 21,  9, 28]), u'MEMORY': array([35, 36, 24,  6,  9, 20,  8])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7f244e23e710>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.44 seconds.
