Running in wrapper mode for '8'

Running python job.

[name: "CPU-QUOTA"
int_val: 36
int_val: 51
int_val: 93
int_val: 91
int_val: 90
int_val: 63
int_val: 85
, name: "DISK"
int_val: 32
int_val: 37
int_val: 8
int_val: 16
int_val: 33
int_val: 17
int_val: 39
, name: "MEMORY"
int_val: 29
int_val: 20
int_val: 14
int_val: 20
int_val: 5
int_val: 11
int_val: 22
, name: "NET"
int_val: 31
int_val: 38
int_val: 19
int_val: 27
int_val: 17
int_val: 17
int_val: 32
]
The paramters are {u'CPU-QUOTA': array([36, 51, 93, 91, 90, 63, 85]), u'NET': array([31, 38, 19, 27, 17, 17, 32]), u'DISK': array([32, 37,  8, 16, 33, 17, 39]), u'MEMORY': array([29, 20, 14, 20,  5, 11, 22])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b7b9200>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.45 seconds.
