Running in wrapper mode for '92'

Running python job.

[name: "CPU-QUOTA"
int_val: 9
int_val: 6
int_val: 77
int_val: 72
int_val: 35
int_val: 84
int_val: 96
, name: "DISK"
int_val: 32
int_val: 6
int_val: 28
int_val: 36
int_val: 17
int_val: 40
int_val: 30
, name: "MEMORY"
int_val: 15
int_val: 6
int_val: 31
int_val: 30
int_val: 19
int_val: 14
int_val: 14
, name: "NET"
int_val: 27
int_val: 8
int_val: 35
int_val: 18
int_val: 18
int_val: 17
int_val: 21
]
The paramters are {u'CPU-QUOTA': array([ 9,  6, 77, 72, 35, 84, 96]), u'NET': array([27,  8, 35, 18, 18, 17, 21]), u'DISK': array([32,  6, 28, 36, 17, 40, 30]), u'MEMORY': array([15,  6, 31, 30, 19, 14, 14])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b754cb0>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.45 seconds.
