Running in wrapper mode for '49'

Running python job.

[name: "CPU-QUOTA"
int_val: 95
int_val: 59
int_val: 50
int_val: 21
int_val: 8
int_val: 83
int_val: 56
, name: "DISK"
int_val: 32
int_val: 5
int_val: 36
int_val: 13
int_val: 19
int_val: 33
int_val: 32
, name: "MEMORY"
int_val: 34
int_val: 26
int_val: 11
int_val: 19
int_val: 13
int_val: 20
int_val: 30
, name: "NET"
int_val: 8
int_val: 29
int_val: 26
int_val: 24
int_val: 21
int_val: 27
int_val: 8
]
The paramters are {u'CPU-QUOTA': array([95, 59, 50, 21,  8, 83, 56]), u'NET': array([ 8, 29, 26, 24, 21, 27,  8]), u'DISK': array([32,  5, 36, 13, 19, 33, 32]), u'MEMORY': array([34, 26, 11, 19, 13, 20, 30])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b7b9c20>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
