Running in wrapper mode for '135'

Running python job.

[name: "CPU-QUOTA"
int_val: 49
int_val: 73
int_val: 28
int_val: 62
int_val: 6
int_val: 40
int_val: 53
, name: "DISK"
int_val: 38
int_val: 16
int_val: 28
int_val: 12
int_val: 22
int_val: 19
int_val: 13
, name: "MEMORY"
int_val: 9
int_val: 37
int_val: 27
int_val: 25
int_val: 19
int_val: 33
int_val: 31
, name: "NET"
int_val: 9
int_val: 38
int_val: 34
int_val: 6
int_val: 6
int_val: 20
int_val: 19
]
The paramters are {u'CPU-QUOTA': array([49, 73, 28, 62,  6, 40, 53]), u'NET': array([ 9, 38, 34,  6,  6, 20, 19]), u'DISK': array([38, 16, 28, 12, 22, 19, 13]), u'MEMORY': array([ 9, 37, 27, 25, 19, 33, 31])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7f244e233cb0>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
