Running in wrapper mode for '86'

Running python job.

[name: "CPU-QUOTA"
int_val: 92
int_val: 20
int_val: 12
int_val: 76
int_val: 99
int_val: 38
int_val: 94
, name: "DISK"
int_val: 5
int_val: 10
int_val: 7
int_val: 21
int_val: 30
int_val: 29
int_val: 32
, name: "MEMORY"
int_val: 37
int_val: 31
int_val: 24
int_val: 22
int_val: 8
int_val: 35
int_val: 33
, name: "NET"
int_val: 32
int_val: 6
int_val: 37
int_val: 30
int_val: 12
int_val: 38
int_val: 36
]
The paramters are {u'CPU-QUOTA': array([92, 20, 12, 76, 99, 38, 94]), u'NET': array([32,  6, 37, 30, 12, 38, 36]), u'DISK': array([ 5, 10,  7, 21, 30, 29, 32]), u'MEMORY': array([37, 31, 24, 22,  8, 35, 33])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b766758>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.45 seconds.
