Running in wrapper mode for '93'

Running python job.

[name: "CPU-QUOTA"
int_val: 57
int_val: 54
int_val: 29
int_val: 24
int_val: 83
int_val: 36
int_val: 48
, name: "DISK"
int_val: 14
int_val: 24
int_val: 10
int_val: 18
int_val: 35
int_val: 22
int_val: 12
, name: "MEMORY"
int_val: 33
int_val: 24
int_val: 13
int_val: 12
int_val: 37
int_val: 32
int_val: 32
, name: "NET"
int_val: 9
int_val: 26
int_val: 17
int_val: 36
int_val: 36
int_val: 35
int_val: 39
]
The paramters are {u'CPU-QUOTA': array([57, 54, 29, 24, 83, 36, 48]), u'NET': array([ 9, 26, 17, 36, 36, 35, 39]), u'DISK': array([14, 24, 10, 18, 35, 22, 12]), u'MEMORY': array([33, 24, 13, 12, 37, 32, 32])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b754fc8>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
