Running in wrapper mode for '112'

Running python job.

[name: "CPU-QUOTA"
int_val: 48
int_val: 15
int_val: 74
int_val: 99
int_val: 98
int_val: 45
int_val: 39
, name: "DISK"
int_val: 30
int_val: 36
int_val: 11
int_val: 35
int_val: 9
int_val: 6
int_val: 40
, name: "MEMORY"
int_val: 10
int_val: 29
int_val: 5
int_val: 17
int_val: 18
int_val: 36
int_val: 40
, name: "NET"
int_val: 40
int_val: 27
int_val: 16
int_val: 10
int_val: 12
int_val: 23
int_val: 40
]
The paramters are {u'CPU-QUOTA': array([48, 15, 74, 99, 98, 45, 39]), u'NET': array([40, 27, 16, 10, 12, 23, 40]), u'DISK': array([30, 36, 11, 35,  9,  6, 40]), u'MEMORY': array([10, 29,  5, 17, 18, 36, 40])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b766368>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
