Running in wrapper mode for '138'

Running python job.

[name: "CPU-QUOTA"
int_val: 61
int_val: 37
int_val: 16
int_val: 26
int_val: 42
int_val: 28
int_val: 17
, name: "DISK"
int_val: 34
int_val: 39
int_val: 32
int_val: 34
int_val: 18
int_val: 33
int_val: 36
, name: "MEMORY"
int_val: 5
int_val: 14
int_val: 23
int_val: 21
int_val: 24
int_val: 28
int_val: 36
, name: "NET"
int_val: 13
int_val: 34
int_val: 29
int_val: 29
int_val: 20
int_val: 25
int_val: 33
]
The paramters are {u'CPU-QUOTA': array([61, 37, 16, 26, 42, 28, 17]), u'NET': array([13, 34, 29, 29, 20, 25, 33]), u'DISK': array([34, 39, 32, 34, 18, 33, 36]), u'MEMORY': array([ 5, 14, 23, 21, 24, 28, 36])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7f244e24c1b8>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.46 seconds.
